### ISSUE TITLE
This condones the usage of terrible interview practices.

### ISSUE THREAD

**Issue by plasticalligator** [jerrak0s/CsharpInterviewQuestions#2]
Anyone interviewing using or supporting the usage of questions that have zero real-world relevance to day-to-day development should be fired on the spot and then crucified upside down covered in honey on a 105°F summer day and left in a field full of fire ants. Thank you and have a nice day =)

**Comment by LeYvan** [comment]
I was thinking something along the lines of _thank you for giving me this red flag"_. Finish this interview and never think about it again.
